import { Injectable, NotFoundException, ForbiddenException } from '@nestjs/common'; import { JwtService } from '@nestjs/jwt'; import { prisma } from '@nexgile/db'; import { AuthUser } from '@nexgile/auth'; import bcrypt from 'bcrypt'; import { CalculationResult } from '@nexgile/shared-types'; import { Queue } from 'bullmq';
const money = (v: unknown) => Number(v || 0);
@Injectable()
export class CoreService {
  constructor(private readonly jwt: JwtService) {}
  private readonly syncQueue = new Queue('mock-custodian-sync', { connection: { url: process.env.REDIS_URL || 'redis://localhost:6379' } });
  async login(email: string, password: string) { const person = await prisma.person.findUnique({ where: { email }, include: { roles: true } }); if (!person || !(await bcrypt.compare(password, person.passwordHash))) throw new ForbiddenException('Invalid email or password'); const roles = person.roles.map(({ role, scopeType, scopeId }) => ({ role, scopeType, scopeId })); return { accessToken: this.jwt.sign({ sub: person.id, email: person.email, roles }), person: { id: person.id, email: person.email, name: person.name, roles } }; }
  async me(id: string) { const person = await prisma.person.findUnique({ where: { id }, include: { roles: true, household: true } }); if (!person) throw new NotFoundException(); return person; }
  private canAccess(user: AuthUser, householdId: string) { if (user.roles.some(r => r.role === 'compliance')) return true; return user.roles.some(r => r.scopeType === 'Household' && r.scopeId === householdId) || user.roles.some(r => r.role === 'advisor' && r.scopeType === 'AdvisorTeam'); }
  async household(user: AuthUser, id: string) { if (!this.canAccess(user, id)) throw new ForbiddenException(); const household = await prisma.household.findUnique({ where: { id }, include: { people: { select: { id: true, name: true, email: true } }, accounts: { include: { custodian: true } } } }); if (!household) throw new NotFoundException(); return household; }
  async accounts(user: AuthUser, householdId: string) { await this.household(user, householdId); const rows = await prisma.account.findMany({ where: { householdId }, include: { custodian: true, holdings: { include: { security: true } } } }); return rows.map(a => ({ ...a, netWorth: a.holdings.reduce((sum, h) => sum + money(h.quantity) * money(h.costBasis), 0) })); }
  async account(user: AuthUser, id: string) { const row = await prisma.account.findUnique({ where: { id }, include: { household: true, custodian: true } }); if (!row) throw new NotFoundException(); if (!this.canAccess(user, row.householdId)) throw new ForbiddenException(); return row; }
  async holdings(user: AuthUser, id: string) { await this.account(user, id); return prisma.holding.findMany({ where: { accountId: id }, include: { security: true, taxLots: true } }); }
  async transactions(user: AuthUser, id: string, filters: { from?: string; to?: string; type?: string }) { await this.account(user, id); return prisma.transaction.findMany({ where: { accountId: id, type: filters.type, occurredAt: { gte: filters.from ? new Date(filters.from) : undefined, lte: filters.to ? new Date(filters.to) : undefined } }, orderBy: { occurredAt: 'desc' } }); }
  async netWorth(user: AuthUser, householdId: string) { const accounts = await this.accounts(user, householdId); const byAssetClass: Record<string, number> = {}; for (const a of accounts) for (const h of a.holdings) { const key = h.security.assetClass; byAssetClass[key] = (byAssetClass[key] || 0) + money(h.quantity) * money(h.costBasis); } return { householdId, total: Object.values(byAssetClass).reduce((a, b) => a + b, 0), byAssetClass, asOf: new Date().toISOString() }; }
  async performance(user: AuthUser, householdId: string): Promise<CalculationResult<{ period: string; returnPct: number }>> { await this.household(user, householdId); return { value: { period: '1Y', returnPct: 0 }, asOf: new Date().toISOString(), method: 'transaction_weighted_placeholder', assumptions: {}, limitations: ['Performance is based on seeded holdings and is not investment advice.', 'Part 2 may replace this with a benchmark-aware calculation.'], computedAt: new Date().toISOString() }; }
  async goals(user: AuthUser, householdId: string) { await this.household(user, householdId); return prisma.goal.findMany({ where: { householdId }, include: { scenarios: true } }); }
  async createGoal(user: AuthUser, householdId: string, body: any) { await this.household(user, householdId); const row = await prisma.goal.create({ data: { householdId, type: body.type, name: body.name, targetAmount: body.targetAmount, targetDate: body.targetDate ? new Date(body.targetDate) : null } }); await this.audit(user.sub, 'Goal', row.id, 'create', null, row); return row; }
  async scenario(user: AuthUser, goalId: string, assumptions: Record<string, number>) { const goal = await prisma.goal.findUnique({ where: { id: goalId } }); if (!goal) throw new NotFoundException(); await this.household(user, goal.householdId); const years = Math.max(0, ((goal.targetDate?.getTime() || Date.now()) - Date.now()) / 31557600000); const rate = assumptions.rateOfReturn || 0; const contribution = assumptions.contributionAmount || 0; const initial = assumptions.initialAmount || 0; const value = initial * Math.pow(1 + rate, years) + (rate ? contribution * ((Math.pow(1 + rate, years) - 1) / rate) : contribution * years); const result: CalculationResult<{ projectedAmount: number; targetAmount: number | null }> = { value: { projectedAmount: value, targetAmount: goal.targetAmount ? money(goal.targetAmount) : null }, asOf: new Date().toISOString(), method: 'compound_growth_deterministic', assumptions, limitations: ['Does not model market volatility; see Monte Carlo simulation for probability-weighted outcomes.', 'Excludes fees, taxes, and changes in contribution behavior.'], computedAt: new Date().toISOString() }; const row = await prisma.scenario.create({ data: { goalId, assumptions, result: JSON.parse(JSON.stringify(result)) } }); await this.audit(user.sub, 'Goal', goalId, 'scenario_create', null, row); return result; }
  async documents(user: AuthUser, householdId: string) { await this.household(user, householdId); return prisma.document.findMany({ where: { householdId }, orderBy: { createdAt: 'desc' } }); }
  async document(user: AuthUser, id: string) { const doc = await prisma.document.findUnique({ where: { id } }); if (!doc) throw new NotFoundException(); if (doc.householdId) await this.household(user, doc.householdId); return doc; }
  async createDocument(user: AuthUser, body: any) { if (body.householdId) await this.household(user, body.householdId); const doc = await prisma.document.create({ data: body }); await this.audit(user.sub, 'Document', doc.id, 'create', null, doc); return { ...doc, upload: { method: 'local-placeholder', url: doc.fileUrl } }; }
  async notifications(user: AuthUser, personId: string) { if (user.sub !== personId && !user.roles.some(r => r.role === 'advisor' || r.role === 'compliance')) throw new ForbiddenException(); return prisma.notification.findMany({ where: { personId }, orderBy: { createdAt: 'desc' } }); }
  async readNotification(user: AuthUser, id: string) { const n = await prisma.notification.findUnique({ where: { id } }); if (!n) throw new NotFoundException(); if (n.personId !== user.sub) throw new ForbiddenException(); return prisma.notification.update({ where: { id }, data: { read: true } }); }
  async audit(actorId: string, entityType: string, entityId: string, action: string, before: any, after: any) { return prisma.auditEvent.create({ data: { actorId, entityType, entityId, action, before: before || undefined, after: after || undefined } }); }
  async audits(user: AuthUser, q: any) { if (!user.roles.some(r => ['advisor', 'compliance'].includes(r.role))) throw new ForbiddenException(); return prisma.auditEvent.findMany({ where: { entityType: q.entityType, entityId: q.entityId, createdAt: { gte: q.from ? new Date(q.from) : undefined, lte: q.to ? new Date(q.to) : undefined } }, orderBy: { createdAt: 'desc' } }); }
  async enqueueSync(user: AuthUser, accountId: string) { await this.account(user, accountId); const job = await this.syncQueue.add('refresh-account', { accountId, actorId: user.sub }, { removeOnComplete: 100, removeOnFail: 100 }); return { jobId: job.id, status: 'queued' }; }
  async syncStatus(jobId: string) { const job = await this.syncQueue.getJob(jobId); if (!job) throw new NotFoundException('Sync job not found'); return { jobId, status: await job.getState(), result: job.returnvalue ?? undefined, failedReason: job.failedReason ?? undefined }; }
}
